# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8066c1a1081f11882d3ebf3bec65b4b232d6c49c87208e935fa84ac29d1bfe073ca4b09a332b6735bfbc8be08bf8df84051f3baa89af4bd2685d9dcc678dbc8f

test:
  secret_key_base: d4eeaf306ccd57bf24df31c2c6760025c03564001d3a2a90d9776f2fa30b5da163d433f414793e74c3b1758242e6f96808b0a8c9e33704e08eae5525608c67a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
